In [2]:
import tensorflow as tf
import numpy as np

In [22]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5]))

In [23]:
iterator = dataset.make_one_shot_iterator()
one_element = iterator.get_next()

In [24]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())


In [25]:
for i in range(5):
    print(sess.run(one_element))

1
2
3
4
5


In [36]:
dataset = tf.data.Dataset.from_tensor_slices(np.random.uniform(size=(2, 5)))
# slices操作将简单dataset的第一个维度切片，生成数组，make_one_shot_iterator

In [37]:
iterator = dataset.make_one_shot_iterator()
one_element = iterator.get_next()
for i in range(2):
    print(sess.run(one_element))
                  

[0.16773771 0.78141369 0.03562735 0.73576428 0.16160163]
[0.61473138 0.10854704 0.08336758 0.33948811 0.57980436]


In [45]:
# 复杂模型，传入字典
dataset = tf.data.Dataset.from_tensor_slices(
    {
        "a": np.array([1,2,34,4,6], dtype=float),
        "b":a_tensor
    }
)

In [47]:
iterator = dataset.make_one_shot_iterator()
elememt = iterator.get_next()

In [48]:
for i in range(5):
    print(sess.run(elememt))

{'a': 1.0, 'b': array([0.62092569, 0.97133812, 0.41408603])}
{'a': 2.0, 'b': array([0.47709276, 0.65416435, 0.55964332])}
{'a': 34.0, 'b': array([0.67867697, 0.24333056, 0.2036523 ])}
{'a': 4.0, 'b': array([0.05477889, 0.39518868, 0.65027499])}
{'a': 6.0, 'b': array([0.88209504, 0.29629261, 0.52985807])}


In [49]:
# 传入元组
dataset = tf.data.Dataset.from_tensor_slices(
  (np.array([1.0, 2.0, 3.0, 4.0, 5.0]), np.random.uniform(size=(5, 2)))
)
iterator = dataset.make_one_shot_iterator()
elememt = iterator.get_next()
for i in range(5):
    print(sess.run(elememt))

(1.0, array([0.94092266, 0.88924503]))
(2.0, array([0.34999822, 0.84249087]))
(3.0, array([0.25617197, 0.97419291]))
(4.0, array([0.69650834, 0.5351583 ]))
(5.0, array([0.66118422, 0.24437363]))


## 对Dataset中的元素做变换：Transformation
Dataset支持一类特殊的操作：Transformation。一个Dataset通过Transformation变成一个新的Dataset。通常我们可以通过Transformation完成数据变换，打乱，组成batch，生成epoch等一系列操作。

# （1） map
map接收一个函数，Dataset中的每个元素都会被当作这个函数的输入，并将函数返回值作为新的Dataset，如我们可以对dataset中每个元素的值加1：


In [51]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1.0, 2.0, 3.0, 4.0, 5.0]))
dataset = dataset.map(lambda x: x + 1) # 2.0, 3.0, 4.0, 5.0, 6.0
iterator = dataset.make_one_shot_iterator()
elememt = iterator.get_next()
for i in range(5):
    print(sess.run(elememt))

2.0
3.0
4.0
5.0
6.0


In [4]:
a_tensor = np.random.uniform(size=(32,2))

In [5]:
a_tensor

array([[6.91866654e-01, 6.75803462e-01],
       [7.35215491e-01, 6.91985379e-05],
       [1.37530062e-01, 4.26140761e-01],
       [8.08570695e-01, 2.03581802e-01],
       [8.75870229e-01, 2.56227717e-01],
       [8.71063655e-01, 1.37931809e-02],
       [5.63622091e-01, 8.97932829e-01],
       [7.37399836e-01, 5.91953683e-01],
       [6.04090252e-01, 8.40840540e-01],
       [7.18532068e-01, 7.03300239e-01],
       [9.76262178e-01, 9.99472760e-01],
       [5.58646346e-01, 8.64448403e-01],
       [7.88792136e-01, 8.81352443e-01],
       [8.80516210e-01, 2.99083345e-01],
       [8.85938262e-01, 1.22541376e-01],
       [8.46058564e-01, 7.17079109e-01],
       [9.92507510e-01, 7.41406734e-01],
       [5.08311983e-01, 1.39771816e-01],
       [7.30743828e-01, 2.05734787e-02],
       [2.46872845e-01, 2.01264585e-01],
       [7.95425582e-01, 6.74491632e-01],
       [9.55073395e-01, 5.18130028e-01],
       [5.23810287e-01, 9.97334055e-01],
       [4.44275159e-01, 4.34323626e-01],
       [6.052644

In [14]:
dataset = tf.data.Dataset.from_tensor_slices(a_tensor)
dataset = dataset.map(lambda x: x + 1) # 2.0, 3.0, 4.0, 5.0, 6.0
dataset.batch(4)
iters = dataset.make_initializable_iterator()
# dataset.prefetch(1)
# iterat = tf.data.Iterator.from_structure((4, ()))
# elememt = iterator.get_next()
# for i in range(5):
#     print(sess.run(elememt))

In [17]:
iters.initializer(dataset)
element = iters.get_next()

TypeError: 'Operation' object is not callable

In [16]:
for i in range(4):
    print(element)

Tensor("IteratorGetNext:0", shape=(2,), dtype=float64)
Tensor("IteratorGetNext:0", shape=(2,), dtype=float64)
Tensor("IteratorGetNext:0", shape=(2,), dtype=float64)
Tensor("IteratorGetNext:0", shape=(2,), dtype=float64)
